baseurl = "https://jahyun-dev.github.io"
languageCode = "en"
title = "DEV LOG"
author = "Jahyun Gu"
canonifyurls = true
theme = "hucore"
disqusShortname = "jhlog"

[taxonomies]
tag = "tags"
category = "categories"

[params]
keywords = ["cryptocurrency", "programming"]
author = "Jahyun Koo"
sharingicons = true

