baseurl = "http://jahyun-dev.github.io/"
title = "DEV LOG"
author = "Jahyun Gu"
canonifyurls = true
languagecode = "en"
theme = "hucore"
disqusShortname = "jhlog"

[taxonomies]
tag = "tags"
category = "categories"

[params]
keywords = ["cryptocurrency", "programming"]
author = "Jahyun Koo"
sharingicons = true

